import Head from 'next/head';
import styles from '@/styles/Home.module.scss'; // @ : 루트경로
import Header from '@/components/Header';
import Image from 'next/image';
import pic from '@/public/img/pic.jpg';
import { useEffect } from 'react';

// api 라우팅: 서버요청 처리를 위해서는 express 프레임워크를 활용
// -> next에서는 api폴더 안쪽에 서버쪽 요청 및 응답에 대한 라우팅 설정 가능
// api 폴더 안쪽의 파일명이 라우터 요청명으로 자동 설정 (ex. /api/hello)

export default function Home() {
	// 서버쪽에서 프리렌더된 페이지를 가져온 이후
	// 클라이언트쪽에서 다시 서버쪽 요청 가능
	// next 자체적으로 서버쪽 요청, 응답 처리
	useEffect(() => {
		// api 폴더 안쪽의 hello.js에 서버요청 처리
		fetch('/api/hello')
			.then((res) => res.json())
			.then((json) => console.log(json));
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Header />
				<h1>Main</h1>

				<div className={styles.pic}>
					<Image src={pic} alt='pic' fill quality={50} />
				</div>

				<div className={styles.pic}>
					<Image
						src='https://images.unsplash.com/photo-1604998103924-89e012e5265a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80'
						alt='pic'
						fill
						quality={50}
					/>
				</div>
			</main>
		</>
	);
}
